// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunislNhI2KCiKiKJPI9QTCiSu5zFlRaA',
    appId: '1:303725499171:web:ae6184ea59aaaa5b9cf296',
    messagingSenderId: '303725499171',
    projectId: 'newbeginning-76a3e',
    authDomain: 'newbeginning-76a3e.firebaseapp.com',
    storageBucket: 'newbeginning-76a3e.appspot.com',
    measurementId: 'G-V549ZWJTYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-CFAUzDc7K26YTKME_s5hqaVPwtPZTA',
    appId: '1:303725499171:android:3b2724df0316d0779cf296',
    messagingSenderId: '303725499171',
    projectId: 'newbeginning-76a3e',
    storageBucket: 'newbeginning-76a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vDXoPTXGOU85bI-vOnmsGzYGnOji54s',
    appId: '1:303725499171:ios:2b8ce9496164a6e19cf296',
    messagingSenderId: '303725499171',
    projectId: 'newbeginning-76a3e',
    storageBucket: 'newbeginning-76a3e.appspot.com',
    iosClientId: '303725499171-3rtvoil992fjcfkdug9r7ru0gjpcs0n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vDXoPTXGOU85bI-vOnmsGzYGnOji54s',
    appId: '1:303725499171:ios:2b8ce9496164a6e19cf296',
    messagingSenderId: '303725499171',
    projectId: 'newbeginning-76a3e',
    storageBucket: 'newbeginning-76a3e.appspot.com',
    iosClientId: '303725499171-3rtvoil992fjcfkdug9r7ru0gjpcs0n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
